# Generated by Django 2.1.7 on 2019-02-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_auto_20190218_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabprosessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.PositiveIntegerField()),
                ('servicetype', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('destnation', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('Pickuptime', models.TimeField()),
                ('issuedto', models.CharField(max_length=250)),
                ('Drivername', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('fare', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
                ('Empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer_Db')),
            ],
        ),
    ]
