# Generated by Django 2.1.7 on 2019-02-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_Db',
            fields=[
                ('User_type', models.CharField(max_length=250)),
                ('Empid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=250)),
                ('Mname', models.CharField(max_length=250)),
                ('Lname', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Phone', models.PositiveIntegerField(max_length=10)),
                ('Address', models.TextField()),
                ('Mgname', models.CharField(max_length=250)),
                ('Mg_email', models.CharField(max_length=250)),
                ('Location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role_Per',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=250)),
                ('perr', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='consumer_db',
            name='Role_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Role_Per'),
        ),
    ]
