# Generated by Django 2.1.7 on 2019-02-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer_db',
            old_name='Empid',
            new_name='empid',
        ),
    ]
